import type { Resource } from "@/types/content";

/** Tools, course materials, and paper readings referenced by the syllabus. */
export const resources: Resource[] = [
  {
    id: "python",
    slug: "python",
    title: "Python",
    href: "https://docs.python.org/3/",
    category: "tools",
    publish: true,
    description: "Primary programming language for course workshops.",
    external: true,
  },
  {
    id: "numpy",
    slug: "numpy",
    title: "NumPy",
    href: "https://numpy.org/doc/stable/",
    category: "tools",
    publish: true,
    description: "Numerical computing foundation used with Pandas.",
    external: true,
  },
  {
    id: "pandas",
    slug: "pandas",
    title: "Pandas",
    href: "https://pandas.pydata.org/docs/",
    category: "tools",
    publish: true,
    description: "Tabular data analysis and manipulation.",
    external: true,
  },
  {
    id: "matplotlib",
    slug: "matplotlib",
    title: "Matplotlib",
    href: "https://matplotlib.org/stable/users/index.html",
    category: "tools",
    publish: true,
    description: "Core plotting library for visualization workshops.",
    external: true,
  },
  {
    id: "seaborn",
    slug: "seaborn",
    title: "Seaborn",
    href: "https://seaborn.pydata.org/",
    category: "tools",
    publish: true,
    description: "Statistical visualization helpers on top of Matplotlib.",
    external: true,
  },
  {
    id: "sql",
    slug: "sql",
    title: "SQL (SQLite documentation)",
    href: "https://www.sqlite.org/docs.html",
    category: "tools",
    publish: true,
    description: "Relational querying reference for the databases module.",
    external: true,
  },
  {
    id: "scikit-learn",
    slug: "scikit-learn",
    title: "scikit-learn",
    href: "https://scikit-learn.org/stable/",
    category: "tools",
    publish: true,
    description: "Classical machine-learning toolkit used with regression and related topics.",
    external: true,
  },
  {
    id: "pytorch",
    slug: "pytorch",
    title: "PyTorch",
    href: "https://pytorch.org/docs/stable/index.html",
    category: "tools",
    publish: true,
    description: "Deep-learning framework referenced in neural-network workshops.",
    external: true,
  },
  {
    id: "tensorflow",
    slug: "tensorflow",
    title: "TensorFlow",
    href: "https://www.tensorflow.org/api_docs",
    category: "tools",
    publish: true,
    description: "Deep-learning framework referenced alongside PyTorch.",
    external: true,
  },
  {
    id: "networkx",
    slug: "networkx",
    title: "NetworkX",
    href: "https://networkx.org/documentation/stable/",
    category: "tools",
    publish: true,
    description: "Network analysis toolkit referenced with causality workshops.",
    external: true,
  },
  {
    id: "plotly",
    slug: "plotly",
    title: "Plotly",
    href: "https://plotly.com/python/",
    category: "tools",
    publish: true,
    description: "Interactive visualization toolkit referenced with causality workshops.",
    external: true,
  },
  {
    id: "isl",
    slug: "introduction-to-statistical-learning",
    title: "An Introduction to Statistical Learning",
    href: "https://www.statlearning.com/",
    category: "readings",
    publish: true,
    description:
      "Primary statistical-learning reference family cited for probability, regression, and classical ML topics (Tibshirani et al.).",
    external: true,
  },
  {
    id: "levine-cs182",
    slug: "sergey-levine-cs182",
    title: "Sergey Levine — Designing, Visualizing and Understanding Deep Neural Networks (Berkeley CS W182 / 282A)",
    href: "https://cs182sp21.github.io/",
    category: "courses",
    publish: true,
    description:
      "Deep learning course site (Spring 2021) with lecture slides, discussions, and homework topics covering nets, CNNs, RNNs, transformers, RL, and generative models — cited for deep-learning foundations in this syllabus.",
    external: true,
  },
  {
    id: "karpathy-zero-to-hero",
    slug: "andrej-karpathy-zero-to-hero",
    title: "Andrej Karpathy — Neural Networks: Zero to Hero",
    href: "https://karpathy.ai/zero-to-hero.html",
    category: "courses",
    publish: true,
    description:
      "Lecture series on building neural nets and a small GPT from scratch; practical reference for the transformers / small-LLM workshop track.",
    external: true,
  },
  {
    id: "karpathy-nn-zero-to-hero-github",
    slug: "andrej-karpathy-nn-zero-to-hero-github",
    title: "Andrej Karpathy — nn-zero-to-hero (notebooks)",
    href: "https://github.com/karpathy/nn-zero-to-hero",
    category: "courses",
    publish: true,
    description:
      "Jupyter notebooks that accompany the Zero to Hero video lectures.",
    external: true,
  },
  {
    id: "karpathy-zero-to-hero-playlist",
    slug: "andrej-karpathy-zero-to-hero-playlist",
    title: "Andrej Karpathy — Zero to Hero (YouTube playlist)",
    href: "https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ",
    category: "courses",
    publish: true,
    description: "Video lectures for the Zero to Hero series.",
    external: true,
  },
  {
    id: "ddpm-ho-2020",
    slug: "ddpm-ho-jain-abbeel-2020",
    title: "Denoising Diffusion Probabilistic Models (Ho, Jain, Abbeel)",
    href: "https://arxiv.org/abs/2006.11239",
    category: "readings",
    publish: true,
    description:
      "Canonical DDPM paper (NeurIPS 2020) for the diffusion-models module.",
    external: true,
  },
  {
    id: "song-ermon-score-matching-2019",
    slug: "song-ermon-score-matching-2019",
    title:
      "Generative Modeling by Estimating Gradients of the Data Distribution (Song & Ermon)",
    href: "https://arxiv.org/abs/1907.05600",
    category: "readings",
    publish: true,
    description:
      "Score matching with Langevin dynamics / NCSN (NeurIPS 2019) — foundational score-based generative modeling paper by Yang Song et al.",
    external: true,
  },
  {
    id: "song-score-based-sde-2021",
    slug: "song-score-based-sde-2021",
    title:
      "Score-Based Generative Modeling through Stochastic Differential Equations (Song et al.)",
    href: "https://arxiv.org/abs/2011.13456",
    category: "readings",
    publish: true,
    description:
      "Unifies score matching (SMLD) and DDPM under continuous-time SDEs (ICLR 2021); core reading for score-based / diffusion connections.",
    external: true,
  },
];
