/**
 * Staff roster.
 *
 * Contacts (optional — omit until real):
 *   email: "name@sharif.edu"
 *   telegram: "@handle"  // or "handle" or "https://t.me/handle"
 *
 * Photos: drop a square WebP/JPEG/PNG into `public/images/staff/`, then set:
 *   photo: { src: "/images/staff/<filename>", alt: "<Name>, <role>" }
 *
 * Add more TAs as separate entries with role: "ta", then reference their `id`
 * from assignment `taIds` in content/assignments.ts.
 */
import type { StaffMember } from "@/types/content";

export const staff: StaffMember[] = [
  {
    id: "babak-hossein-khalaj",
    slug: "babak-hossein-khalaj",
    name: "Dr. Babak Hossein Khalaj",
    role: "instructor",
    title: "Instructor",
    publish: true,
    order: 1,
    bio: "Full Professor of Electrical Engineering, Sharif University of Technology.",
    email: "khalaj@sharif.edu",
    // telegram: "@…",
    photo: { src: "/images/staff/babak-khalaj.jpg", alt: "Dr. Babak Hossein Khalaj, Instructor" },
  },
  {
    id: "amir-hossein-saberi",
    slug: "amir-hossein-saberi",
    name: "Dr. Amir Hossein Saberi",
    role: "instructor",
    title: "Instructor",
    publish: true,
    order: 2,
    bio: "Lecturer in Electrical Engineering, Sharif University of Technology",
    email: "seyedsaberi@gmail.com",
    // telegram: "@…",
    photo: { src: "/images/staff/amir-hossein-saberi.jpg", alt: "Dr. Amir Hossein Saberi, Instructor" },
  },
  {
    id: "mohammad-eshtehardian",
    slug: "mohammad-eshtehardian",
    name: "Mohammad Eshtehardian",
    role: "ta",
    title: "Head Teaching Assistant",
    publish: true,
    order: 3,
    bio: "PhD student of Electrical Engineering, Communications Systems, Sharif University of Technology.",
    email: "mohammad.eshtehardian@sharif.edu",
    // telegram: "@…",
    photo: { src: "/images/staff/mohammad-eshtehardian.png", alt: "Mohammad Eshtehardian" },
  },
  {
    id: "pooya-gholami",
    slug: "pooya-gholami",
    name: "Pooya Gholami",
    role: "ta",
    title: "Teaching Assistant",
    publish: true,
    order: 4,
    bio: "MSc graduate of Electrical Engineering, Communications Systems, Sharif University of Technology.",
    email: "pooya.ghb@gmail.com",
    // telegram: "@…",
    photo: { src: "/images/staff/pooya-gholami.jpg", alt: "Pooya Gholami" },
  },
  {
    id: "kiarash-rashidi",
    slug: "kiarash-rashidi",
    name: "Kiarash Rashidi",
    role: "ta",
    title: "Teaching Assistant",
    publish: true,
    order: 4,
    bio: "MSc student of Electrical Engineering, Communications Systems, Sharif University of Technology.",
    email: "kia.rashidi@sharif.edu",
    // telegram: "@…",
    photo: { src: "/images/staff/kiarash-rashidi.jpg", alt: "Kiarash Rashidi" },
  },
  {
    id: "hossein-soleimani",
    slug: "hossein-soleimani",
    name: "Hossein Soleimani",
    role: "ta",
    title: "Teaching Assistant",
    publish: true,
    order: 4,
    bio: "MSc student of Electrical Engineering, Digital Electronics, Sharif University of Technology.",
    email: "soleimani.hossein@ee.sharif.edu",
    // telegram: "@…",
    photo: { src: "/images/staff/hossein-soleimani.jpg", alt: "Hossein Soleimani" },
  },
  {
    id: "mohammad-hossein-momeni",
    slug: "mohammad-hossein-momeni",
    name: "Mohammad Hossein Momeni Hamaneh",
    role: "ta",
    title: "Teaching Assistant",
    publish: true,
    order: 4,
    bio: "MSc student of Electrical Engineering, Communications Systems, Sharif University of Technology.",
    email: "Mohammadh.momenih81@sharif.edu",
    // telegram: "@…",
    photo: { src: "/images/staff/mohammad-hossein-momeni.jpg", alt: "Mohammad Hossein Momeni Hamaneh" },
  },
  {
    id: "amir-reza-azari",
    slug: "amir-reza-azari",
    name: "Amir Reza Azari",
    role: "ta",
    title: "Teaching Assistant",
    publish: true,
    order: 4,
    bio: "MSc student of Computer Engineering, Artificial Intelligence, Sharif University of Technology.",
    email: "amirrrr.azariii123@sharif.edu",
    // telegram: "@…",
    photo: { src: "/images/staff/amir-reza-azari.jpg", alt: "Amir Reza Azari" },
  },
  {
    id: "shahab-hosseini",
    slug: "shahab-hosseini",
    name: "Shahab Hosseini",
    role: "ta",
    title: "Teaching Assistant",
    publish: true,
    order: 4,
    bio: "BSc graduate of Computer Engineering, Software Engineering, Sharif University of Technology.",
    email: "s.hosseini306@gmail.com",
    // telegram: "@…",
    photo: { src: "/images/staff/shahab-hosseini.png", alt: "Shahab Hosseini" },
  },
  {
    id: "sahar-semsarha",
    slug: "sahar-semsarha",
    name: "Sahar Semsarha",
    role: "ta",
    title: "Teaching Assistant",
    publish: true,
    order: 4,
    bio: "BSc student of Electrical Engineering, Bioelectric, Sharif University of Technology.",
    email: "Sahar.sems@gmail.com",
    // telegram: "@…",
    photo: { src: "/images/staff/sahar-semsarha.jpg", alt: "Sahar Semsarha" },
  },
  {
    id: "iman-alizadeh-fakouri",
    slug: "iman-alizadeh-fakouri",
    name: "Iman Alizadeh Fakouri",
    role: "ta",
    title: "Teaching Assistant",
    publish: true,
    order: 4,
    bio: "BSc student of Electrical Engineering, Communications Systems, Sharif University of Technology.",
    email: "imanfakury1382@gmail.com",
    // telegram: "@…",
    photo: { src: "/images/staff/iman-alizadeh-fakouri.jpg", alt: "Iman Alizadeh Fakouri" },
  },
  {
    id: "mohammadali-naderi",
    slug: "mohammadali-naderi",
    name: "Mohammad Ali Naderi",
    role: "ta",
    title: "Teaching Assistant",
    publish: true,
    order: 4,
    bio: "BSc student of Electrical Engineering, Communications Systems, Sharif University of Technology.",
    email: "mali_naderi@ee.sharif.edu",
    // telegram: "@…",
    photo: { src: "/images/staff/mohammadali-naderi.jpg", alt: "Mohammad Ali Naderi" },
  },
  {
    id: "darya-azaddel",
    slug: "darya-azaddel",
    name: "Darya Azaddel",
    role: "ta",
    title: "Teaching Assistant",
    publish: true,
    order: 4,
    bio: "BSc student of Electrical Engineering, Communications Systems, Sharif University of Technology.",
    email: "darya.azaddel18@sharif.edu",
    // telegram: "@…",
    photo: { src: "/images/staff/darya-azaddel.jpg", alt: "Darya Azaddel" },
  },
  {
    id: "ali-rezaei",
    slug: "ali-rezaei",
    name: "Ali Rezaei",
    role: "ta",
    title: "Teaching Assistant",
    publish: true,
    order: 4,
    bio: "BSc student of Electrical Engineering, Communications Systems, Sharif University of Technology.",
    email: "ali.rezaei84@sharif.edu",
    // telegram: "@…",
    photo: { src: "/images/staff/ali-rezaei.jpg", alt: "Ali Rezaei" },
  },
  {
    id: "aida-aryafar",
    slug: "aida-aryafar",
    name: "Aida Aryafar",
    role: "ta",
    title: "Teaching Assistant",
    publish: true,
    order: 4,
    bio: "BSc student of Electrical Engineering, Bioelectric, Sharif University of Technology.",
    email: "aida_aryafar@ee.sharif.edu",
    // telegram: "@…",
    photo: { src: "/images/staff/aida-aryafar.jpg", alt: "Aida Aryafar" },
  },
  {
    id: "saba-atashfaraz",
    slug: "saba-atashfaraz",
    name: "Saba Atashfaraz",
    role: "ta",
    title: "Teaching Assistant",
    publish: true,
    order: 4,
    bio: "BSc student of Electrical Engineering, Communications Systems, Sharif University of Technology.",
    email: "saba.atashfaraz84@sharif.edu",
    // telegram: "@…",
    photo: { src: "/images/staff/saba-atashfaraz.jpg", alt: "Saba Atashfaraz" },
  },
];
